/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SecoStandaloneSetup extends SecoStandaloneSetupGenerated {

	def static void doSetup() {
		new SecoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
