/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSecoScopeProvider extends DelegatingScopeProvider {
}
