/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

import de.upb.sede.dsl.seco.FieldValue;

/**
 * A sample validator interface for {@link de.upb.sede.dsl.seco.Argument}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was
 * generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled
 * with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArgumentValidator {
	boolean validate();

	boolean validateIndexed(boolean value);

	boolean validateIndex(int value);

	boolean validateParameterName(String value);

	boolean validateValue(FieldValue value);
}
