/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

/**
 * A sample validator interface for
 * {@link de.upb.sede.dsl.seco.DeploymentProcedure}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentProcedureValidator {
	boolean validate();

	boolean validateSource(String value);

	boolean validateAct(String value);

	boolean validateFetch(String value);

	boolean validateName(String value);
}
