/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

/**
 * A sample validator interface for
 * {@link de.upb.sede.dsl.seco.DeploymentDependency}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentDependencyValidator {
	boolean validate();

	boolean validateDeployment(String value);

	boolean validateOrder(int value);
}
