/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

import de.upb.sede.dsl.seco.EntityMethodParam;

import java.util.List;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for
 * {@link de.upb.sede.dsl.seco.EntityMethodParamSignature}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityMethodParamSignatureValidator {
	boolean validate();

	boolean validateParameters(EList<EntityMethodParam> value);

	boolean validateOutputs(EList<EntityMethodParam> value);

	boolean validateParameters(List<EntityMethodParam> value);

	boolean validateOutputs(List<EntityMethodParam> value);
}
