/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

import de.upb.sede.dsl.seco.DeploymentDependency;
import de.upb.sede.dsl.seco.DeploymentProcedure;

import java.util.List;

/**
 * A sample validator interface for
 * {@link de.upb.sede.dsl.seco.EntityDeploymentDefinition}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityDeploymentDefinitionValidator {
	boolean validate();

	boolean validateProcedures(List<DeploymentProcedure> value);

	boolean validateProviders(List<DeploymentProcedure> value);

	boolean validateDependencies(List<DeploymentDependency> value);

	boolean validateQualifiedName(String value);
}
