/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

import de.upb.sede.dsl.seco.Field;
import de.upb.sede.dsl.seco.FieldValue;
import de.upb.sede.dsl.seco.Operation;

/**
 * A sample validator interface for {@link de.upb.sede.dsl.seco.FieldValue}.
 * This doesn't really do anything, and it's not a real EMF artifact. It was
 * generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled
 * with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FieldValueValidator {
	boolean validate();

	boolean validateCast(boolean value);

	boolean validateCastTarget(String value);

	boolean validateCastValue(FieldValue value);

	boolean validateNumber(String value);

	boolean validateString(String value);

	boolean validateBool(String value);

	boolean validateNull(boolean value);

	boolean validateOperation(Operation value);

	boolean validateField(Field value);
}
