/**
 *
 * $Id$
 */
package de.upb.sede.dsl.seco.validation;

import de.upb.sede.dsl.seco.Argument;
import de.upb.sede.dsl.seco.Field;

import java.util.List;

/**
 * A sample validator interface for {@link de.upb.sede.dsl.seco.Operation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationValidator {
	boolean validate();

	boolean validateContextField(Field value);
	boolean validateEntityName(String value);
	boolean validateMethod(String value);
	boolean validateArgs(List<Argument> value);
}
