/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.upb.sede.dsl.SecoRuntimeModule;
import de.upb.sede.dsl.SecoStandaloneSetup;
import de.upb.sede.dsl.ide.SecoIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SecoIdeSetup extends SecoStandaloneSetup {
  @Override
  public Injector createInjector() {
    SecoRuntimeModule _secoRuntimeModule = new SecoRuntimeModule();
    SecoIdeModule _secoIdeModule = new SecoIdeModule();
    return Guice.createInjector(Modules2.mixin(_secoRuntimeModule, _secoIdeModule));
  }
}
