/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.ide;

import de.upb.sede.dsl.ide.AbstractSecoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SecoIdeModule extends AbstractSecoIdeModule {
}
