/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.ide

import com.google.inject.Guice
import de.upb.sede.dsl.SecoRuntimeModule
import de.upb.sede.dsl.SecoStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SecoIdeSetup extends SecoStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SecoRuntimeModule, new SecoIdeModule))
	}
	
}
