@startuml

skinparam defaultFontName "Avenir"
skinparam defaultFontSize 13
skinparam classBorderColor black
skinparam ArrowColor black

interface "IQualifiable" {
  qualifier : String
  metaTags : List<String>
  simpleName : String
}

interface "CommentAware" {
  comments : List<String>
}


class "MethodDesc" {
  signatures : List<ISignatureDesc>
}

class "MethodParameterDesc" {
  type : String
  name : String
  fixedValue : String
  callByValue : boolean
}

class "ServiceCollectionDesc" {
  services : List<IServiceDesc>
  dataTypes : List<IDataTypeDesc>
}

class "ServiceDesc" {
  methods : List<IMethodDesc>
  interfaces : List<String>
  isAbstract : boolean
  fieldTypes : Map<String, String>

}

class "SignatureDesc" {
  inputs : List<IMethodParameterDesc>
  outputs : List<IMethodParameterDesc>
  isPure : boolean
  isContextFree : boolean

}

class "DataTypeDesc" {
  semanticType : String
}

'"CommentAware" <|-- "MethodDesc"
'"CommentAware" <|-- "ServiceCollectionDesc"
'"CommentAware" <|-- "ServiceDesc"
'"CommentAware" <|-- "SignatureDesc"
'"CommentAware" <|-- "DataTypeDesc"
"IQualifiable" <|-- "MethodDesc"
"IQualifiable" <|-- "ServiceCollectionDesc"
"IQualifiable" <|-- "ServiceDesc"
"IQualifiable" <|-- "DataTypeDesc"

"MethodDesc" --> "*" "SignatureDesc" : signatures
"ServiceCollectionDesc" --> "*" "DataTypeDesc" : dataTypes
"ServiceCollectionDesc" --> "*" "ServiceDesc" : services
"ServiceDesc" --> "*" "MethodDesc" : methods
"SignatureDesc" "*" --> "*" "MethodParameterDesc" : inputs/outputs


@enduml
