/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.upb.sede.edd.api;

import de.upb.sede.requests.deploy.ExecutorDemandFulfillment;
import de.upb.sede.requests.deploy.ExecutorDemandRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-03T11:35:15.474Z[GMT]")
@Api(value = "demandUnit", description = "the demandUnit API")
public interface DemandUnitApi {

    @ApiOperation(value = "Demand executors that fullfill the requested services.", nickname = "demandUnitPost", notes = "", response = ExecutorDemandRequest.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Returns a potentially partial service fullfillment.", response = ExecutorDemandFulfillment.class) })
    @RequestMapping(value = "/demandUnit",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ExecutorDemandFulfillment> demandUnitPost(@ApiParam(value = "", required = true) @Valid @RequestBody ExecutorDemandRequest body);

}
