/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.upb.sede.edd.api;

import de.upb.sede.edd.deploy.deplengine.InstallationReport;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-03T11:35:15.474Z[GMT]")
@Api(value = "preparations", description = "the preparations API")
public interface PreparationsApi {

    @ApiOperation(value = "Returns the last prepare logs and the currenty installed versions.", nickname = "preparationsGet", notes = "", response = InstallationReport.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Installation description for each installed service collection.", response = InstallationReport.class, responseContainer = "List") })
    @RequestMapping(value = "/preparations",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<InstallationReport>> preparationsGet();

}
