FROM sede:java

# RUN apt-get update && apt-get install -y --no-install-recommends \
#    graphviz \
#    ttf-freefont

RUN apk update && apk add \
	graphviz \
    	ttf-freefont

ENV DOT_PATH=/usr/bin/dot

COPY ./run-gateway-template/configs /configs