/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.validation;

import de.upb.sede.dsl.validation.AbstractSecoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SecoValidator extends AbstractSecoValidator {
}
