/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.upb.sede.dsl.SecoRuntimeModule;
import de.upb.sede.dsl.SecoStandaloneSetup;
import de.upb.sede.dsl.ide.SecoIdeModule;
import de.upb.sede.dsl.web.SecoWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class SecoWebSetup extends SecoStandaloneSetup {
  @Override
  public Injector createInjector() {
    SecoRuntimeModule _secoRuntimeModule = new SecoRuntimeModule();
    SecoIdeModule _secoIdeModule = new SecoIdeModule();
    SecoWebModule _secoWebModule = new SecoWebModule();
    return Guice.createInjector(Modules2.mixin(_secoRuntimeModule, _secoIdeModule, _secoWebModule));
  }
}
