/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.web;

import de.upb.sede.dsl.web.AbstractSecoWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class SecoWebModule extends AbstractSecoWebModule {
}
