/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SecoWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSecoWebModule extends DefaultWebModule {

}
