/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.seco;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#isIsIndexed <em>Is Indexed</em>}</li>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#getIndex <em>Index</em>}</li>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#isIsNumb <em>Is Numb</em>}</li>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#isIsString <em>Is String</em>}</li>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#isIsBool <em>Is Bool</em>}</li>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#isIsNull <em>Is Null</em>}</li>
 *   <li>{@link de.upb.sede.dsl.seco.Parameter#isIsField <em>Is Field</em>}</li>
 * </ul>
 *
 * @see de.upb.sede.dsl.seco.SecoPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Indexed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Indexed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Indexed</em>' attribute.
   * @see #setIsIndexed(boolean)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_IsIndexed()
   * @model
   * @generated
   */
  boolean isIsIndexed();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#isIsIndexed <em>Is Indexed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Indexed</em>' attribute.
   * @see #isIsIndexed()
   * @generated
   */
  void setIsIndexed(boolean value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

  /**
   * Returns the value of the '<em><b>Is Numb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Numb</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Numb</em>' attribute.
   * @see #setIsNumb(boolean)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_IsNumb()
   * @model
   * @generated
   */
  boolean isIsNumb();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#isIsNumb <em>Is Numb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Numb</em>' attribute.
   * @see #isIsNumb()
   * @generated
   */
  void setIsNumb(boolean value);

  /**
   * Returns the value of the '<em><b>Is String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is String</em>' attribute.
   * @see #setIsString(boolean)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_IsString()
   * @model
   * @generated
   */
  boolean isIsString();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#isIsString <em>Is String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is String</em>' attribute.
   * @see #isIsString()
   * @generated
   */
  void setIsString(boolean value);

  /**
   * Returns the value of the '<em><b>Is Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Bool</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Bool</em>' attribute.
   * @see #setIsBool(boolean)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_IsBool()
   * @model
   * @generated
   */
  boolean isIsBool();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#isIsBool <em>Is Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Bool</em>' attribute.
   * @see #isIsBool()
   * @generated
   */
  void setIsBool(boolean value);

  /**
   * Returns the value of the '<em><b>Is Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Null</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Null</em>' attribute.
   * @see #setIsNull(boolean)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_IsNull()
   * @model
   * @generated
   */
  boolean isIsNull();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#isIsNull <em>Is Null</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Null</em>' attribute.
   * @see #isIsNull()
   * @generated
   */
  void setIsNull(boolean value);

  /**
   * Returns the value of the '<em><b>Is Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Field</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Field</em>' attribute.
   * @see #setIsField(boolean)
   * @see de.upb.sede.dsl.seco.SecoPackage#getParameter_IsField()
   * @model
   * @generated
   */
  boolean isIsField();

  /**
   * Sets the value of the '{@link de.upb.sede.dsl.seco.Parameter#isIsField <em>Is Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Field</em>' attribute.
   * @see #isIsField()
   * @generated
   */
  void setIsField(boolean value);

} // Parameter
