/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.seco;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.upb.sede.dsl.seco.SecoFactory
 * @model kind="package"
 * @generated
 */
public interface SecoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seco";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.de/sede/dsl/Seco";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seco";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SecoPackage eINSTANCE = de.upb.sede.dsl.seco.impl.SecoPackageImpl.init();

  /**
   * The meta object id for the '{@link de.upb.sede.dsl.seco.impl.EntriesImpl <em>Entries</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.upb.sede.dsl.seco.impl.EntriesImpl
   * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getEntries()
   * @generated
   */
  int ENTRIES = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRIES__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Entries</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.upb.sede.dsl.seco.impl.EntryImpl <em>Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.upb.sede.dsl.seco.impl.EntryImpl
   * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getEntry()
   * @generated
   */
  int ENTRY = 1;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY__INSTRUCTION = 0;

  /**
   * The number of structural features of the '<em>Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.upb.sede.dsl.seco.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.upb.sede.dsl.seco.impl.InstructionImpl
   * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 2;

  /**
   * The feature id for the '<em><b>Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__FIELD = 0;

  /**
   * The feature id for the '<em><b>Context</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__CONTEXT = 1;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__METHOD = 2;

  /**
   * The feature id for the '<em><b>Inputs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__INPUTS = 3;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.upb.sede.dsl.seco.impl.ParametersImpl <em>Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.upb.sede.dsl.seco.impl.ParametersImpl
   * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getParameters()
   * @generated
   */
  int PARAMETERS = 3;

  /**
   * The feature id for the '<em><b>Inputs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS__INPUTS = 0;

  /**
   * The number of structural features of the '<em>Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.upb.sede.dsl.seco.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.upb.sede.dsl.seco.impl.ParameterImpl
   * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 4;

  /**
   * The feature id for the '<em><b>Is Indexed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IS_INDEXED = 0;

  /**
   * The feature id for the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__INDEX = 1;

  /**
   * The feature id for the '<em><b>Is Numb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IS_NUMB = 2;

  /**
   * The feature id for the '<em><b>Is String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IS_STRING = 3;

  /**
   * The feature id for the '<em><b>Is Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IS_BOOL = 4;

  /**
   * The feature id for the '<em><b>Is Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IS_NULL = 5;

  /**
   * The feature id for the '<em><b>Is Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IS_FIELD = 6;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 7;


  /**
   * Returns the meta object for class '{@link de.upb.sede.dsl.seco.Entries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entries</em>'.
   * @see de.upb.sede.dsl.seco.Entries
   * @generated
   */
  EClass getEntries();

  /**
   * Returns the meta object for the containment reference list '{@link de.upb.sede.dsl.seco.Entries#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see de.upb.sede.dsl.seco.Entries#getElements()
   * @see #getEntries()
   * @generated
   */
  EReference getEntries_Elements();

  /**
   * Returns the meta object for class '{@link de.upb.sede.dsl.seco.Entry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry</em>'.
   * @see de.upb.sede.dsl.seco.Entry
   * @generated
   */
  EClass getEntry();

  /**
   * Returns the meta object for the containment reference '{@link de.upb.sede.dsl.seco.Entry#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see de.upb.sede.dsl.seco.Entry#getInstruction()
   * @see #getEntry()
   * @generated
   */
  EReference getEntry_Instruction();

  /**
   * Returns the meta object for class '{@link de.upb.sede.dsl.seco.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see de.upb.sede.dsl.seco.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Instruction#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field</em>'.
   * @see de.upb.sede.dsl.seco.Instruction#getField()
   * @see #getInstruction()
   * @generated
   */
  EAttribute getInstruction_Field();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Instruction#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Context</em>'.
   * @see de.upb.sede.dsl.seco.Instruction#getContext()
   * @see #getInstruction()
   * @generated
   */
  EAttribute getInstruction_Context();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Instruction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see de.upb.sede.dsl.seco.Instruction#getMethod()
   * @see #getInstruction()
   * @generated
   */
  EAttribute getInstruction_Method();

  /**
   * Returns the meta object for the containment reference '{@link de.upb.sede.dsl.seco.Instruction#getInputs <em>Inputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inputs</em>'.
   * @see de.upb.sede.dsl.seco.Instruction#getInputs()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Inputs();

  /**
   * Returns the meta object for class '{@link de.upb.sede.dsl.seco.Parameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameters</em>'.
   * @see de.upb.sede.dsl.seco.Parameters
   * @generated
   */
  EClass getParameters();

  /**
   * Returns the meta object for the containment reference list '{@link de.upb.sede.dsl.seco.Parameters#getInputs <em>Inputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inputs</em>'.
   * @see de.upb.sede.dsl.seco.Parameters#getInputs()
   * @see #getParameters()
   * @generated
   */
  EReference getParameters_Inputs();

  /**
   * Returns the meta object for class '{@link de.upb.sede.dsl.seco.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see de.upb.sede.dsl.seco.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#isIsIndexed <em>Is Indexed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Indexed</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#isIsIndexed()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_IsIndexed();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Index</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#getIndex()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Index();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#isIsNumb <em>Is Numb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Numb</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#isIsNumb()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_IsNumb();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#isIsString <em>Is String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is String</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#isIsString()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_IsString();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#isIsBool <em>Is Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Bool</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#isIsBool()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_IsBool();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#isIsNull <em>Is Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Null</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#isIsNull()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_IsNull();

  /**
   * Returns the meta object for the attribute '{@link de.upb.sede.dsl.seco.Parameter#isIsField <em>Is Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Field</em>'.
   * @see de.upb.sede.dsl.seco.Parameter#isIsField()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_IsField();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SecoFactory getSecoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.upb.sede.dsl.seco.impl.EntriesImpl <em>Entries</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.upb.sede.dsl.seco.impl.EntriesImpl
     * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getEntries()
     * @generated
     */
    EClass ENTRIES = eINSTANCE.getEntries();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTRIES__ELEMENTS = eINSTANCE.getEntries_Elements();

    /**
     * The meta object literal for the '{@link de.upb.sede.dsl.seco.impl.EntryImpl <em>Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.upb.sede.dsl.seco.impl.EntryImpl
     * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getEntry()
     * @generated
     */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTRY__INSTRUCTION = eINSTANCE.getEntry_Instruction();

    /**
     * The meta object literal for the '{@link de.upb.sede.dsl.seco.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.upb.sede.dsl.seco.impl.InstructionImpl
     * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUCTION__FIELD = eINSTANCE.getInstruction_Field();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUCTION__CONTEXT = eINSTANCE.getInstruction_Context();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUCTION__METHOD = eINSTANCE.getInstruction_Method();

    /**
     * The meta object literal for the '<em><b>Inputs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__INPUTS = eINSTANCE.getInstruction_Inputs();

    /**
     * The meta object literal for the '{@link de.upb.sede.dsl.seco.impl.ParametersImpl <em>Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.upb.sede.dsl.seco.impl.ParametersImpl
     * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getParameters()
     * @generated
     */
    EClass PARAMETERS = eINSTANCE.getParameters();

    /**
     * The meta object literal for the '<em><b>Inputs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETERS__INPUTS = eINSTANCE.getParameters_Inputs();

    /**
     * The meta object literal for the '{@link de.upb.sede.dsl.seco.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.upb.sede.dsl.seco.impl.ParameterImpl
     * @see de.upb.sede.dsl.seco.impl.SecoPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Is Indexed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IS_INDEXED = eINSTANCE.getParameter_IsIndexed();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__INDEX = eINSTANCE.getParameter_Index();

    /**
     * The meta object literal for the '<em><b>Is Numb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IS_NUMB = eINSTANCE.getParameter_IsNumb();

    /**
     * The meta object literal for the '<em><b>Is String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IS_STRING = eINSTANCE.getParameter_IsString();

    /**
     * The meta object literal for the '<em><b>Is Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IS_BOOL = eINSTANCE.getParameter_IsBool();

    /**
     * The meta object literal for the '<em><b>Is Null</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IS_NULL = eINSTANCE.getParameter_IsNull();

    /**
     * The meta object literal for the '<em><b>Is Field</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IS_FIELD = eINSTANCE.getParameter_IsField();

  }

} //SecoPackage
