= Deployment in SEDE - `SKETCH`
:toc: left
:pr-rel-root: ../../../../../
:pr-docs: {pr-rel-root}SEDE.docs/base/src/docs/asciidoc/
:easy-block-link: https://easybuild.readthedocs.io/en/latest/Concepts_and_Terminology.html#easyblocks

This is the documentation on the *deployment procedures* of SEDE components.
This document and the described tools and methods are *work in progress*.

== EDD

The Executor Deployment Daemon (EDD) is a tool that manages software build and installation and integration into SEDE components, especially SEDE executors.

The following needs are the main motivations for its creation:

* *flexible and configurable* installation procedures
* fully *automated*
* remotely *accessible*
* automatic *dependency resolution*
* time and space *efficient*

=== Blocks

Software build, installation and runtime procedures are defined in jvm classes, called `Blocks`.
This notion follows the example of {easy-block-link}[Easyblocks] from the `EasyBuild` installation framework which has proven as a clean and working solution for software deployment.

Blocks rely on these concepts:

. Inheritance:
Extend *generic* blocks that implement a procedure using *standard tools* (e.g. Maven, CMake, VirtualEnv)
. Inversion of Control:
Dependencies on other blocks are resolved by *dependency injection*
. Event Bus:
Blocks can *subscribe to events* from other blocks to add *custom actions*, or *publish own events* for future extensions.

=== Build activity flow

The following uml activity diagram illustrates the process of software build in EDD:

[plantuml,"edd-overview",svg]
....
include::{pr-docs}../plantuml/edd-overview.activity-diag.plantuml[]
....

