/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl;

import de.upb.sede.dsl.SecoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecoStandaloneSetup extends SecoStandaloneSetupGenerated {
  public static void doSetup() {
    new SecoStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
