/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl;

import de.upb.sede.dsl.AbstractSecoRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecoRuntimeModule extends AbstractSecoRuntimeModule {
}
