/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.parser.antlr;

import com.google.inject.Inject;
import de.upb.sede.dsl.parser.antlr.internal.InternalSecoParser;
import de.upb.sede.dsl.services.SecoGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SecoParser extends AbstractAntlrParser {

	@Inject
	private SecoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSecoParser createParser(XtextTokenStream stream) {
		return new InternalSecoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Entries";
	}

	public SecoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SecoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
