/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SecoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/upb/sede/dsl/parser/antlr/internal/InternalSeco.tokens");
	}
}
