/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.scoping;

import de.upb.sede.dsl.scoping.AbstractSecoScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SecoScopeProvider extends AbstractSecoScopeProvider {
}
