/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.tests;

import com.google.inject.Inject;

import de.upb.sede.dsl.seco.Assignment;
import de.upb.sede.dsl.seco.EntityName;
import de.upb.sede.dsl.seco.Entries;
import de.upb.sede.dsl.seco.SecoFactory;
import de.upb.sede.dsl.seco.impl.EntityNameImpl;
import de.upb.sede.dsl.tests.SecoInjectorProvider;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(SecoInjectorProvider.class)
@SuppressWarnings("all")
public class SecoParseTest {
  @Inject
  private ParseHelper<Entries> parseHelper;
  
  @Test
  public void testCast() {
	  
	
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("a = (Number) b;");
      _builder.newLine();
      final Entries result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
      Assignment a = ((Assignment) result.getElements().get(0));
      Assertions.assertTrue(a.getValue().isCast());
      EntityName numberEntity = SecoFactory.eINSTANCE.createEntityName();
      numberEntity.setName("Number");
      Assertions.assertTrue(EcoreUtil.equals(numberEntity,  a.getValue().getCastTarget()));
      
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
