/**
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.tests;

import com.google.inject.Inject;
import com.ibm.icu.impl.Assert;

import de.upb.sede.dsl.SecoUtil;
import de.upb.sede.dsl.seco.Assignment;
import de.upb.sede.dsl.seco.DeploymentDependency;
import de.upb.sede.dsl.seco.EntityClassDefinition;
import de.upb.sede.dsl.seco.EntityDeploymentDefinition;
import de.upb.sede.dsl.seco.EntityMethod;
import de.upb.sede.dsl.seco.Entries;
import de.upb.sede.dsl.seco.SecoFactory;
import de.upb.sede.dsl.seco.SecoPackage;
import de.upb.sede.dsl.tests.SecoInjectorProvider;

import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.util.Arrays;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.json.simple.JSONObject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(SecoInjectorProvider.class)
@SuppressWarnings("all")
public class SecoUtilTest {
  @Inject
  private ParseHelper<Entries> parseHelper;
  
  @Test
  public void testOperation() throws Exception {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("a = ($Number) b;");
      _builder.newLine();
      final Entries result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
      Assignment a = ((Assignment) result.getInstructions().get(0));
      Assertions.assertTrue(a.getValue().isCast());
      Assertions.assertEquals("Number",  a.getValue().getCastTarget());
      
      a = EcoreUtil.copy(a);
      Entries entries = new Entries();
      entries.getInstructions().add(a);
      System.out.println(SecoUtil.serialize(entries));
  }

  @Test
  public void testConverter() throws IOException {
		  EPackage.Registry.INSTANCE.put(SecoPackage.eNS_URI, SecoPackage.class);
	      StringConcatenation _builder = new StringConcatenation();
	      
	      _builder.append("class: a.b.C wraps $d.se.F extends $g.H, a.ai.J {");
	      _builder.newLine();
	      _builder.append("method:  !Construct (Number, String, some.Entity) -> (Bool, $some.other.Entity);");
	      _builder.newLine();
	      _builder.append("method:  Construct ($Number, String, some.Entity) -> (Bool, some.other.Entity);");
	      _builder.newLine();
	      _builder.append("casts to: $Some.Other.Entity;");
	      _builder.newLine();
	      _builder.append("}");
	      _builder.newLine();
//	      System.out.println(_builder.toString() + "\n");
	      
	      Entries result = SecoUtil.parseSources(_builder.toString());
	      Assertions.assertNotNull(result);
	      EntityClassDefinition a =  (result.getEntities().get(0));
	      Assertions.assertEquals(a.getQualifiedName(), "a.b.C");
	      Assertions.assertEquals(a.getWrappedEntity(), "d.se.F");
	      Assertions.assertEquals(a.getBaseEntities(), Arrays.asList("g.H", "a.ai.J"));

	      EntityMethod m1 = a.getMethods().get(0);
	      EntityMethod m2 = a.getMethods().get(1);
	      
	      Assertions.assertTrue(EcoreUtil.equals(m1, m2));
	      
	      Assertions.assertEquals(a.getCasts().get(0).getResultingEntity(), "Some.Other.Entity");

	      Entries entries = EcoreUtil.copy(result);
	      System.out.println(SecoUtil.serialize(entries));
	      System.out.println(entries);
  }
  @Test
  public void testJson() throws IOException {
      String seco = "class: a {"
      				+ "method:  !Construct (Number, String, some.Entity) -> (Bool, $some.other.Entity)"
      				+ "runtime: {"
      				+	"\"Hello\":\"world!\",\n"
      				+	"\"Number\":1"
      				+"}"
      				+ ";"
      		+ "}";
      
      Entries entries = EcoreUtil.copy(SecoUtil.parseSources(seco));
      System.out.println(seco);
      System.out.println(entries.getEntities().get(0).getMethods().get(0).getRuntimeInfo());
      System.out.println(entries.toString());
  }
  

  @Test
  public void testDeployment() throws IOException {
      String seco = "deployment: apple { "
				+ "procedure: build gradle_java git \"http://example.com.git\";"
  				+ "procedure: name=verify act=bash fetch=http source=\"http://apple.verify\";"
  				+ "dependency: food;"
  				+ "dependency: fruit(PRE-RUN);"
  				+ "dependency: cut(POST-RUN);"
  				+ "dependency: eat(-  \n11);"
      		+ "}";
      
      System.out.println(seco);
      
      Entries entries = EcoreUtil.copy(SecoUtil.parseSources(seco));
      EntityDeploymentDefinition apple = entries.getDeployments().get(0);
      assertEquals("build", apple.getProcedures().get(0).getName());
      assertEquals("http://example.com.git", apple.getProcedures().get(0).getSource());
      
      DeploymentDependency dep0 = apple.getDependencies().get(0);
      assertEquals("food", dep0.getDeployment());
      assertEquals(-100, dep0.getOrder());
      
      DeploymentDependency dep1 = apple.getDependencies().get(1);
      assertEquals("fruit", dep1.getDeployment());
      assertEquals(-10, dep1.getOrder());
      
      DeploymentDependency dep2 = apple.getDependencies().get(2);
      assertEquals("cut", dep2.getDeployment());
      assertEquals(10, dep2.getOrder());
      
      DeploymentDependency dep3 = apple.getDependencies().get(3);
      assertEquals("eat", dep3.getDeployment());
      assertEquals(- 11, dep3.getOrder());
      
      System.out.println("Formatted to:\n" + entries.toString());
  }
  @Test
  public void testNumbers() throws IOException {
      String seco = "a = -10;"
      		+ "a = - 10;"
      		+ "- 10 . 3;";
      
      System.out.println(seco);
      
      Entries entries = EcoreUtil.copy(SecoUtil.parseSources(seco));

      Assignment a0 = (Assignment) entries.getInstructions().get(0);
      assertEquals("-10", a0.getValue().getNumber());
      Assignment a1 = (Assignment) entries.getInstructions().get(1);
      assertEquals("-10", a1.getValue().getNumber());
      Assignment a2 = (Assignment) entries.getInstructions().get(2);
      assertEquals("-10.3", a2.getValue().getNumber());
      
      System.out.println("Formatted to:\n" + entries.toString());
  }
  @Test
  public void testMethodInstructions() throws IOException {
      String seco = "class: A {"
			      		+ "method: A() -> ()"
			      		+ 	"do: {a=2;}"
			      		+ ";"
		      		+ "}";
		      
      System.out.println(seco);
      
      Entries entries = EcoreUtil.copy(SecoUtil.parseSources(seco));

      System.out.println("Formatted to:\n" + entries.toString());
  }
  
}
