/*
 * generated by Xtext 2.15.0
 */
package de.upb.sede.dsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SecoWebModule extends AbstractSecoWebModule {
}
