/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class C2Data_C2ImageMagickCaller */

#ifndef _Included_C2Data_C2ImageMagickCaller
#define _Included_C2Data_C2ImageMagickCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    im_env_up
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_C2Data_C2ImageMagickCaller_im_1env_1up
  (JNIEnv *, jobject);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    im_env_down
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_C2Data_C2ImageMagickCaller_im_1env_1down
  (JNIEnv *, jobject);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    open_image
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_C2Data_C2ImageMagickCaller_open_1image
  (JNIEnv *, jobject, jstring);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    close_image
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_C2Data_C2ImageMagickCaller_close_1image
  (JNIEnv *, jobject, jlong);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    create_image
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_C2Data_C2ImageMagickCaller_create_1image
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    read_image
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_C2Data_C2ImageMagickCaller_read_1image
  (JNIEnv *, jobject, jlong);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    write_image
 * Signature: (J[S)V
 */
JNIEXPORT void JNICALL Java_C2Data_C2ImageMagickCaller_write_1image
  (JNIEnv *, jobject, jlong, jshortArray);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    get_image_rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_C2Data_C2ImageMagickCaller_get_1image_1rows
  (JNIEnv *, jobject, jlong);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    get_image_columns
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_C2Data_C2ImageMagickCaller_get_1image_1columns
  (JNIEnv *, jobject, jlong);

/*
 * Class:     C2Data_C2ImageMagickCaller
 * Method:    set_new_path
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_C2Data_C2ImageMagickCaller_set_1new_1path
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
